### ISSUE TITLE
Can not extract models

### ISSUE THREAD

**Issue by BLMTuan** [zhouhang95/neox_tools#11]
Does this tool still work for the game?
Onmyoji game files now are sorted  into model.npk
but when I extract with O extractor.py
It showed "The system cannot find the path specified" and didnt give out any file.
![Screenshot 2021-10-05 001024](https://user-images.githubusercontent.com/35293841/135894390-6202720d-3914-4a7a-b72f-79f44f134241.png)

Or may be I did something wrong
Could you take a look please
Thank you

**Comment by zhouhang95** [comment]
follow the commands
don't "i think it's also ok"

**Comment by zhouhang95** [comment]
you can show me your input command

**Comment by BLMTuan** [comment]
Thank you very much for your replies 
But I managed to make it work
I pointed python directly to game files in setting folder Program Files (x86) 
So I think it wont work if *.npk files are separately extracted
Thank you for making wonderful tools

**Comment by zhouhang95** [comment]
Have fun!
