### ISSUE TITLE
Question: Messiah MPK file decryption!

### ISSUE THREAD

**Issue by dnextcom** [zhouhang95/neox_tools#12]
Hi! This is not really an issue on your submission but a question.

Have you seen the new Netease's engine Messiah? It uses MPK files and they seem to have a different encryption system. Do you think they might be using something similar to the NPK you figured out here?

I uploaded a few files here in case you want to see what I mean:
https://www.mediafire.com/file/0t38kkqwvjxkqxd/e46a07c1c54d66e3e77251ce383cfc3a/file
https://www.mediafire.com/file/hslml9a0qddk75z/0f98fac7babf2dfab4c388ff67a281b1/file
https://www.mediafire.com/file/yl58ph0ytj96hxm/ef2f6ecf63a082be43aa04f839f7d578/file

Any help on how to get access to those files would be really appreciated, thanks!

**Comment by zhouhang95** [comment]
total different format
