### ISSUE TITLE
第五人格最新npk无法解密

### ISSUE THREAD

**Issue by JennyTanlol** [zhouhang95/neox_tools#14]
您好 抱歉打扰，第五人格最新的npk包好像更换了加密 无法用此工具解密了><

**Comment by JennyTanlol** [comment]
抱歉 忘记提供样本 加密后npk样本 https://forum.xentax.com/viewtopic.php?t=26676
加密前npk样本https://www.mediafire.com/file/pjmz2jq5kguf4cp/dm65_survivor_m.npk/file

**Comment by zhouhang95** [comment]
我不玩这游戏 不支持

**Comment by zhouhang95** [comment]
每个游戏 密钥是不一样的

https://blog.sina.com.cn/s/blog_b4721dbb0102yqoj.html
这个也许可以

**Comment by JennyTanlol** [comment]
> 每个游戏 密钥是不一样的
> 
> https://blog.sina.com.cn/s/blog_b4721dbb0102yqoj.html 这个也许可以

找到其他方式解决了！感谢回复

**Comment by celery411** [comment]
> > 每个游戏 密钥是不一样的
> > https://blog.sina.com.cn/s/blog_b4721dbb0102yqoj.html 这个也许可以
> 
> 找到其他方式解决了！感谢回复

可以分享对您有用的链接吗？🥺
