### ISSUE TITLE
any ideas for neox motion files

### ISSUE THREAD

**Issue by C4nf3ng** [zhouhang95/neox_tools#4]
I tried to parse the motion gis file struct. However I have no idea how to unseriallize pose data bytes into quaternion or euler angle or etc. form. Do you have any idea on that? 
thanks

**Comment by zhouhang95** [comment]
in convert.py,
'''
if ext in ['mesh', 'ktx', 'bnk', 'riff', 'pvr', 'pkm', 'dds']:
'''
->
'''
if True:
'''

**Comment by zhouhang95** [comment]
上逆向 从引擎里查如何解析
掘金上有逆向阴阳师的文章 可以的话 动手试试
