### ISSUE TITLE
幻书启世录

### ISSUE THREAD

**Issue by PriChama** [zhouhang95/neox_tools#7]
Hey, thanks so much for your tool! It works really great. 

Although I've come across a game that doesnt seem to work..
New game called 幻书启世录 (https://hsqsl.163.com/) . I was wondering if you could look at these files? When I use the extractor.py it doesn't give any messages aside from 
"Could Not Find C:\Users\anime\Desktop\Ripping\Files\PC\GMA\neteasehsqsl\char1\*.ktx
Could Not Find C:\Users\anime\Desktop\Ripping\Files\PC\GMA\neteasehsqsl\char1\*.pvr"
And absolutely no files come out at all. 

If you could look at the files for this one that'd be great!

Thanks!

**Comment by zhouhang95** [comment]
Sorry, it's out of my ability.
I watched it and can not know how to unpack it

**Comment by Ruslan16022** [comment]
> Sorry, it's out of my ability.
> I watched it and can not know how to unpack it

Hey. Can u try unpack npk from LifeAfter game?

**Comment by zhouhang95** [comment]
幻书启世录 close servers
